title: Family Travelling Blog
author: Marc
email: edwardsmd88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Travelling around the world for the first time with kids. Lots of new countries and new adventures to be had.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
